### ISSUE TITLE
Please reconsider the naming of this extension.

### ISSUE THREAD

**Issue by sypets** [bmack/modern-template-building#1]
Imagine searching on extensions.typo3.org for "template": https://extensions.typo3.org/?L=0&id=1&tx_solr%5Bq%5D=template

This extension is one of the top hits. While for "old" veterans (like me) it is immediately clear what this is, what about new users? 

I think the word "modern" should not be part of this extension key.

Just my 2c, please feel free to ignore and close.

**Comment by bmack** [comment]
@sypets well, renaming is an option, but probably not as easy to achieve (TYPO3 / TER has no good solution for renaming an extension, just like "replaces" in composer). As an intermediate step I could imagine renaming the "title" of the extension and also the description. In addition, TER could prioritize their search results? giving the extension less prominent promotion?

Also, Google Search delivers a lot of outdated content regarding "Modern Template Building" as well, as this extension name is based on the name of the tutorial (back then), there was a "Futuristic Template Building" 
 tutorial as well. https://docs.typo3.org/typo3cms/extensions/doc_tut_templselect/stable/Manual/Index.html

**Comment by bmack** [comment]
Thinking about it a bit more... I created this extension with a few hours of work to help others using this functionality when upgrading TYPO3 projects. Back then I did not think this might confuse people. However, I do not plan to put a lot of energy in the maintenance of this extension, and I certainly do not want to send the idea out to the world that this extension should be used for newcomers.

For this reason, in order to reduce the amount of work for everyone, I will just delete the extension from TER + packagist, so it does not get promoted anymore.

**Comment by franzholz** [comment]
No, please do never remove this package. It is still needed by the mastertemplate extension.
This is still relevant for users who used TYPO3 in 2004 and still want to be able to upgrade to TYPO3 12 without making much efforts in learning the new Fluid templating. 
This extension has about 370 downloads a month, where only 10 downloads are by the TER. Almost all downloads are done by packagist.

**Comment by bmack** [comment]
Closing the ticket then - thanks @franzholz for your feedback
